//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.University
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesUniversity : DbContext
    {
        public EntitiesUniversity()
            : base("name=EntitiesUniversity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<EmployeesInRooms> EmployeesInRooms { get; set; }
        public virtual DbSet<Facilities> Facilities { get; set; }
        public virtual DbSet<FacilitiesInRooms> FacilitiesInRooms { get; set; }
        public virtual DbSet<Preferences> Preferences { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<Specializations> Specializations { get; set; }
    }
}
